### PR TITLE
Adding linux support(old shallow-backup version)

### PR DESCRIPTION
**Pull request by rods-honorio**
Linux support for and old version of shallow-backup

### CODE REVIEW

**Comment by rods-honorio** [comment]
I was working on an old fork of your application :/ , now a lot of things got refactor, hope you get the idea from this PR. Sorry about it.

**Comment by alichtman** [comment]
Thanks for contributing!

Tag me when you've updated from master and fixed all the conflicts.

**Comment by alichtman** [comment]
@rods-honorio Any update?

**Comment by alichtman** [comment]
I incorporated this work into shallow backup in this commit: 5926b12 

I've credited you as a contributor in the Contributors file. 

Thanks for helping me out.

**Pull request closed without merging**
