### PR TITLE
replaced colorama with ansi codes

### LINKED ISSUE #137: Replace colorama with escape codes
No need for the extra dependency.

```
# ASCII color codes
GREEN = '\033[92m'
GRAY = '\033[90m'
CYAN = '\033[36m'
RED = '\033[31m'
YELLOW = '\033[33m'
END = '\033[0m'
UNDERLINE = '\033[4m'
BOLD = '\033[1m'
```

### PR DESCRIPTION
**Pull request by redpfire**
This PR resolves #137 

I've removed all colorama references from all the files and utilized ANSI codes in a handy table. I did my best to follow your coding standard. I've also tested it and it works pretty well.

Hope you merge.
Best regards.

### CODE REVIEW

**Comment by redpfire** [comment]
Okay. Now it's clear. I'm gonna work on it. :)

**Comment by alichtman** [comment]
I just realized that colorama takes care of a Windows compatibility issue and should not be replaced. The solution is using import aliases, like:

`from colorama import Fore.RED as RED`

**Comment by alichtman** [comment]
Good solution at this point, import colorama things in `stylize.py`.

So:

```
from colorama import Fore, Style

RED = Fore.RED
...
```

**Comment by alichtman** [comment]
I'm currently working on a huge refactoring of the project, so after I get that sorted out, I'll tag you here and you can update from master and fix all the merge conflicts, and then I'll get this merged in.

**Comment by redpfire** [comment]
Okay!

**Comment by alichtman** [comment]
Try pulling from master and resolving those merge conflicts, and then I'll check this out.

**Comment by alichtman** [comment]
I think I have a pretty good solution, actually. I'll merge it into master so you can see what I'm doing.

I declared some generic print functions in `printing.py` to clean up the rest of the code a bit.

```python
def print_bright_blue(text):
	print(Fore.BLUE + Style.BRIGHT + text + Style.RESET_ALL)


def print_bright_red(text):
	print(Fore.RED + Style.BRIGHT + text + Style.RESET_ALL)


def print_bright_yellow(text):
	print(Fore.YELLOW + Style.BRIGHT + text + Style.RESET_ALL)


def print_bright_green(text):
	print(Fore.GREEN + Style.BRIGHT + text + Style.RESET_ALL)
```

I'm now going through the code and refactoring the print statements as much as I can. If you'd like to work on that, that would be helpful. If not, there's plenty of other cool stuff to work on.

**Pull request closed without merging**
